# Generated by Django 5.2.4 on 2025-08-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForestSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('species_name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=50)),
                ('nepal', models.CharField(max_length=50)),
                ('altitude', models.CharField(max_length=50)),
                ('local_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'forest_species',
                'verbose_name_plural': 'forest_species',
                'db_table': 'forest_species',
            },
        ),
        migrations.CreateModel(
            name='HDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('expression', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'hd_model',
                'verbose_name_plural': 'hd_model',
                'db_table': 'hd_model',
            },
        ),
        migrations.CreateModel(
            name='Physiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ecological', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'physiography',
                'verbose_name_plural': 'physiography',
                'db_table': 'physiography',
            },
        ),
        migrations.CreateModel(
            name='SpeciesHDModelMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_a', models.FloatField()),
                ('hd_b', models.FloatField(blank=True, null=True)),
                ('hd_c', models.FloatField(blank=True, null=True)),
                ('hd_model', models.ForeignKey(db_column='hd_model_code', on_delete=django.db.models.deletion.CASCADE, to='mrv.hdmodel', to_field='code')),
                ('physiography', models.ForeignKey(db_column='physio_code', on_delete=django.db.models.deletion.CASCADE, to='mrv.physiography', to_field='code')),
                ('species', models.ForeignKey(db_column='species_code', on_delete=django.db.models.deletion.CASCADE, to='mrv.forestspecies', to_field='code')),
            ],
            options={
                'verbose_name': 'species_hd_model_map',
                'verbose_name_plural': 'species_hd_model_map',
                'db_table': 'species_hd_model_map',
                'unique_together': {('species', 'physiography')},
            },
        ),
    ]
