# Generated by Django 5.2.4 on 2025-08-23 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique project identifier', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Project name can only contain letters, numbers, underscores (_), and hyphens (-).', regex='^[a-zA-Z0-9_-]+$')])),
                ('description', models.TextField(blank=True, help_text='Project description', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_phase', models.IntegerField(choices=[(1, 'Phase 1 - Data Collection'), (2, 'Phase 2 - Analysis'), (3, 'Phase 3 - Validation'), (4, 'Phase 4 - Reporting')], default=1)),
                ('current_step', models.IntegerField(default=1, help_text='Current step within the phase')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'mrv_projects',
                'ordering': ['-last_modified'],
            },
        ),
    ]
