# Generated by Django 5.2.4 on 2025-08-30 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrv', '0002_add_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(help_text='Source schema name from foris_connection', max_length=255)),
                ('table_name', models.CharField(help_text='Source table name from foris_connection', max_length=255)),
                ('action', models.CharField(choices=[('append', 'Append'), ('replace', 'Replace')], default='append', help_text='Whether to append or replace existing data', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('imported_rows', models.IntegerField(default=0, help_text='Number of rows imported')),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in source table')),
                ('description', models.TextField(blank=True, help_text='Import description', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if import failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When import processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When import completed', null=True)),
                ('project', models.ForeignKey(help_text='Project this import belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to='mrv.project')),
            ],
            options={
                'verbose_name': 'Project Data Import',
                'verbose_name_plural': 'Project Data Imports',
                'db_table': 'mrv_project_data_imports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='mrv_project_project_19711a_idx'), models.Index(fields=['created_at'], name='mrv_project_created_401b32_idx')],
            },
        ),
    ]
