# Generated by Django 5.2.4 on 2025-08-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrv', '0003_projectdataimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDataImport',
        ),
    ]
