# Generated by Django 5.2.4 on 2025-11-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrv', '0005_alter_project_current_phase_allometric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.CharField(help_text='Unique plot identifier', max_length=50, primary_key=True, serialize=False)),
                ('col', models.IntegerField(help_text='Column number')),
                ('row', models.IntegerField(help_text='Row number')),
                ('plot_number', models.IntegerField(help_text='Plot number')),
                ('lon', models.FloatField(help_text='Longitude')),
                ('lat', models.FloatField(help_text='Latitude')),
                ('phy_zone', models.IntegerField(blank=True, help_text='Physiography zone code', null=True)),
                ('province', models.CharField(blank=True, help_text='Province name', max_length=255, null=True)),
                ('province_id', models.IntegerField(blank=True, help_text='Province ID', null=True)),
            ],
            options={
                'verbose_name': 'Plot',
                'verbose_name_plural': 'Plots',
                'db_table': 'plots',
                'ordering': ['plot_id'],
                'indexes': [models.Index(fields=['plot_id'], name='plots_plot_id_68c7ff_idx'), models.Index(fields=['col', 'row'], name='plots_col_99a7f6_idx'), models.Index(fields=['phy_zone'], name='plots_phy_zon_a53c45_idx'), models.Index(fields=['province_id'], name='plots_provinc_42a396_idx')],
            },
        ),
    ]
